theme: minima
title: REM Tutorials
description: Tutorials on Relational (Hyper) Event Modeling

header_pages:
  - index.md

include:
  - index.md
  - 01-Introduction-to-REM/index.md
  - 01-Introduction-to-REM/01-Simulating-REM-Data/index.md
  - 01-Introduction-to-REM/02-Alien-Species-Invasions/index.md
  - 02-All-you-need-to-know-RHEM/index.md
  - 02-All-you-need-to-know-RHEM/01-Les-Miserables/index.md
  - 02-All-you-need-to-know-RHEM/02-Scientific-Innovation/index.md

exclude:
  - "**/*.Rmd"

kramdown:
  math_engine: mathjax