---
title: "Empirical Applications (3): Email communication"
author: "Martina Boschi"
date: "2026-04-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Time explains: Modeling a Unimodal Network of Emails in a Company

## Preliminarities

The following section aims to load the necessary packages and import the data. 

```{r pressure, echo=FALSE, message=FALSE, warning=FALSE}
source("script/packages.R")
source("script/covariate.R")
```

```{r eval=FALSE}
email <- read.csv("input/manufacturing.csv", sep = ";")
nrow(email)
range(email$EventDate)
```

```{r eval=FALSE}
# Do not consider auto-email
sel <- which(email[,1]==email[,2])
email <- email[-sel,]

# Consider only unique email
email <- unique(email)

# Consider only one email per time-point
sel <- unique(email$EventDate)
o <- !duplicated(email$EventDate)
email <- email[o,]

# Numerical format of time
# (# of days from the first email)
dates <- email$EventDate
range(dates)
tms <- time_length(seconds(ymd_hms(email[,3])))
tms <- tms-min(tms)+1
tms <- tms/(24*60*60)

# Emails as relational events (s,r,t)
email <- cbind(tms, email[,c(1,2)])
colnames(email) <- c("stp","s1","r1")

# Set of unique senders and receivers
senders <- unique(email$s1)
receivers <- unique(email$r1)
length(senders)
length(receivers)

# Numerical codification of senders and receivers
actors <- unique(c(email$s1, email$r1))
email$s1 <- match(email$s1, actors)
email$r1 <- match(email$r1, actors)
p <- length(actors)

# Potential couples of senders and receivers (risk set)
possible.sr <- matrix(1, nrow = p, ncol = p)
diag(possible.sr) <- 0

save(possible.sr, actors, email, file="input/preliminary-email.RData")
```

## Covariate computation

```{r}
load(file="input/preliminary-email.RData")
p <- length(actors)
```

```{r eval=FALSE}
dat.gam <- NULL
set.seed(1234)

for (i in 2:nrow(email)){

  if(i%%1000==0){print(i)}

  # Fixed response equal to 1
  y <- 1

  # Event information
  stp <- email[i,1]
  s.ev <- email[i,2]
  r.ev <- email[i,3]
  sr.ev <- (r.ev - 1) * p + s.ev

  # Non-event information
  sr.nv <- sample(setdiff(which(possible.sr==1), sr.ev), 1)
  s.nv <- (sr.nv-1)%%p+1
  r.nv <- (sr.nv-1)%/%p+1

  # Covariate difference between event and non-event at the time of the event
  # (covariates for specific event and non event are reported as well);
  covariates.ev <- covariate(data = email,
                             s = s.ev,
                             r = r.ev,
                             stp = stp)
  covariates.nv <- covariate(data = email,
                             s = s.nv,
                             r = r.nv,
                             stp = stp)

  dat.gam <- rbind(dat.gam,
                   c(1, stp,
                     s.ev, r.ev,
                     s.nv, r.nv,
                     covariates.ev[1], covariates.nv[1],
                     covariates.ev[1]- covariates.nv[1],
                     covariates.ev[2], covariates.nv[2],
                     covariates.ev[2]- covariates.nv[2],
                     covariates.ev[3], covariates.nv[3],
                     covariates.ev[3]- covariates.nv[3],
                     covariates.ev[4], covariates.nv[4],
                     covariates.ev[4]- covariates.nv[4],
                     covariates.ev[5], covariates.nv[5],
                     covariates.ev[5]- covariates.nv[5],
                     covariates.ev[6], covariates.nv[6],
                     covariates.ev[6]- covariates.nv[6],
                     covariates.ev[7], covariates.nv[7],
                     covariates.ev[7]- covariates.nv[7],
                     covariates.ev[8], covariates.nv[8],
                     covariates.ev[8]- covariates.nv[8]))
}

dat.gam.complete <- data.frame(
  # Fixed response equal to 1
  y = dat.gam[,1],
  # Event information
  stp = dat.gam[,2],
  s1 = dat.gam[,3],
  r1 = dat.gam[,4],
  # Non-Event information
  s2 = dat.gam[,5],
  r2 = dat.gam[,6],
  # Covariate difference between event and non-event at the time of the event
  # Reciprocity Indicator
  rec1 = dat.gam[,7],
  rec2 = dat.gam[,8],
  rec = dat.gam[,9],
  # Reciprocity Time
  timeRec1 = dat.gam[,10],
  timeRec2 = dat.gam[,11],
  timeRec = dat.gam[,12],
  # Cyclic Closure Indicator
  cyc1 = dat.gam[,13],
  cyc2 = dat.gam[,14],
  cyc = dat.gam[,15],
  # Cyclic Closure Time
  timeCyc1 = dat.gam[,16],
  timeCyc2 = dat.gam[,17],
  timeCyc = dat.gam[,18],
  # Repetition Indicator
  iner1 = dat.gam[,19],
  iner2 = dat.gam[,20],
  iner = dat.gam[,21],
  # Repetition Time
  timeIner1 = dat.gam[,22],
  timeIner2 = dat.gam[,23],
  timeIner = dat.gam[,24],
  # Transitive Closure Indicator
  triad1 = dat.gam[,25],
  triad2 = dat.gam[,26],
  triad = dat.gam[,27],
  # Transitive Closure Time
  timeTriad1 = dat.gam[,28],
  timeTriad2 = dat.gam[,29],
  timeTriad = dat.gam[,30]
)
dat.gam <- dat.gam.complete
save(dat.gam, file="output/dat_gam_no_shift.RData")
```

### Shifting

```{r}
load(file="output/dat_gam_no_shift.RData")
```

```{r eval=FALSE}
set.seed(1234)
T <- max(dat.gam$stp)

shifts <- rexp(p^2,1/T)
dat.gam$event_id <- dat.gam$s1+(dat.gam$r1-1)*p
dat.gam$shifted_stp <- dat.gam$stp + shifts[dat.gam$event_id]
dat.gam$non_stp <- dat.gam$non_s <- dat.gam$non_r <- NA
nonselfloop<-abs(as.vector(1-diag(p)))

for (i in 1:nrow(dat.gam)){
  
  if(i%%1000==0){print(i)}
  atrisk<-nonselfloop*((shifts < dat.gam$shifted_stp[i]) &
                       (shifts+T> dat.gam$shifted_stp[i]))
  non_event_id <- sample(1:p^2,1,prob = atrisk/sum(atrisk))
  dat.gam$non_s[i] <- (non_event_id-1)%%p+1
  dat.gam$non_r[i] <- (non_event_id-1)%/%p+1
  dat.gam$non_stp[i] <- dat.gam$shifted_stp[i] - shifts[non_event_id]
}

for (i in 2:nrow(dat.gam)){

  if(i%%1000==0){print(i)}

  # Fixed response equal to 1
  y <- 1

  # Event information
  stp <- dat.gam$non_stp[i]
  s.nv <- dat.gam$non_s[i]
  r.nv <- dat.gam$non_r[i]

  cov = covariate(data = email, s = s.nv, r = r.nv, stp = stp)
  dat.gam$rec2[i] = cov[1]
  dat.gam$timeRec2[i] = cov[2]
  dat.gam$cyc2[i] = cov[3]
  dat.gam$timeCyc2[i] = cov[4]
  dat.gam$iner2[i] = cov[5]
  dat.gam$timeIner2[i] = cov[6]
  dat.gam$triad2[i] = cov[7]
  dat.gam$timeTriad2[i] = cov[8]

}

colnames(dat.gam)

dat_gam_shifted <- dat.gam[,c("y","stp","s1","r1","s2","r2","rec1", "rec2",
                              "timeRec1","timeRec2","cyc1","cyc2",
                              "timeCyc1","timeCyc2","iner1","iner2",
                              "timeIner1","timeIner2","triad1","triad2",
                              "timeTriad1", "timeTriad2", "non_r","non_s",
                              "non_stp")]

dat_gam_shifted$day1<-floor(dat.gam$stp)
dat_gam_shifted$tod1<-(dat_gam_shifted$stp-dat_gam_shifted$day1)*24

dat_gam_shifted$day2<-floor(dat_gam_shifted$non_stp)
dat_gam_shifted$tod2<-(dat_gam_shifted$non_stp-dat_gam_shifted$day2)*24

dat_gam_shifted$dow1<-dat_gam_shifted$day1%%7
dat_gam_shifted$dow2<-dat_gam_shifted$day2%%7

hist(dat_gam_shifted$day1)
hist(dat_gam_shifted$day2)

hist(dat_gam_shifted$tod1)
hist(dat_gam_shifted$tod2)

hist(dat_gam_shifted$dow1)
hist(dat_gam_shifted$dow2)

save(dat_gam_shifted, file="output/dat_gam_shifted.RData")
```

```{r}
load(file="output/dat_gam_shifted.RData")
```

## Model fitting

### With shifting

```{r eval=FALSE}
Cyc_Mat <- cbind(dat_gam_shifted$timeCyc1,
                 dat_gam_shifted$timeCyc2)

Rep_Mat <- cbind(dat_gam_shifted$timeIner1,
                 dat_gam_shifted$timeIner2)

Weight <- Rec_Mat <- cbind(dat_gam_shifted$timeRec1,
                           dat_gam_shifted$timeRec2)

Trs_Mat <- cbind(dat_gam_shifted$timeTriad1,
                 dat_gam_shifted$timeTriad2)

Tod_Mat <- cbind(dat_gam_shifted$tod1,
                 dat_gam_shifted$tod2)

Dow_Mat <- cbind(dat_gam_shifted$dow1,
                 dat_gam_shifted$dow2)

Time_Mat <- cbind(dat_gam_shifted$stp,
                  dat_gam_shifted$non_stp)

Weight[,1] <- 1
Weight[,2] <- -1

fit_shift <- gam(formula = y ~  - 1 + s(Rec_Mat, by=Weight) +
             s(Trs_Mat, by=Weight) +
             s(Rep_Mat, by=Weight) +
             s(Cyc_Mat, by=Weight) +
             s(Time_Mat, by=Weight) +
             s(Dow_Mat, by=Weight, bs="cc", k=7) +
             s(Tod_Mat, by=Weight, bs="cc"),
           family="binomial"(link = 'logit'), 
           data=dat_gam_shifted)
save(fit_shift, file="output/fit_shift.RData")
```

### Without shifting

```{r eval=FALSE}
Weight <- Cyc_Mat <- cbind(dat.gam$timeCyc1,
                           dat.gam$timeCyc2)

Rep_Mat <- cbind(dat.gam$timeIner1,
                 dat.gam$timeIner2)

Rec_Mat <- cbind(dat.gam$timeRec1,
                 dat.gam$timeRec2)

Trs_Mat <- cbind(dat.gam$timeTriad1,
                 dat.gam$timeTriad2)

Weight[,1] <- 1
Weight[,2] <- -1

fit_noshift <- gam(formula = y ~  - 1 + 
                     s(Rec_Mat, by=Weight) +
                     s(Trs_Mat, by=Weight) +
                     s(Rep_Mat, by=Weight) +
                     s(Cyc_Mat, by=Weight),
                   family="binomial"(link = 'logit'),
                   data=dat.gam)
save(fit_noshift, file="output/fit_noshift.RData")
```

### Results

```{r}
load(file="output/fit_shift.RData")
load(file="output/fit_noshift.RData")
```


```{r}
create_plots <- function(gam_fit, elements, ranges, 
                         labs, titles, subtitle){
  
  viz_obj <- getViz(gam_fit)
  
  plots <- list()
  
  for (element in elements){
    
    x_lab <- labs[element]
    main_title <- titles[element]
    
    sm <- plot(sm(viz_obj, select=element))
    data <- sm$ggObj$data
    if (element <= 4){
      data$trans_x <- -log(data$x)
    } else {
      data$trans_x <- data$x
    }
    data$upper <- data$y + 1.96 * data$se
    data$lower <- data$y - 1.96 * data$se
    
    plots[[element]] <- ggplot(data, aes(x = trans_x, y = y)) +
      geom_line(color = "black", linewidth = 0.8) +
      geom_line(aes(y = upper), linetype = "dashed", color = "black", linewidth = 0.6) +
      geom_line(aes(y = lower), linetype = "dashed", color = "black", linewidth = 0.6) +
      labs(
        x = paste(x_lab),
        y = "Non-Linear Effect",
        title = main_title,
        subtitle = subtitle,
      ) +
      theme_minimal(base_size = 14) +
      theme(
        plot.title = element_text(size = 22, face = "bold", hjust = 0.5),      
        plot.subtitle = element_text(size = 18, face = "bold", hjust = 0.5),      
        axis.title.x = element_text(size = 16),                  
        axis.title.y = element_text(size = 16),                  
        axis.text.x = element_text(size = 16),
        axis.text.y = element_text(size = 16),
        axis.text = element_text(size = 13)                                    
      ) + 
      ylim(c(ranges[element,]))
    
  }
  
  return(plots)
  
}

plots_noshift <- create_plots(gam_fit = fit_noshift, 
                              elements = c(1,2,3,4), 
                              ranges = rbind(c(-3,6),
                                             c(-3,3),
                                             c(-3,9),
                                             c(-2.5,2)),
                              labs = c("Internal reciprocal time", 
                                       "Internal transitive time", 
                                       "Internal repeated time", 
                                       "Internal cyclic time"), 
                              titles = c("Reciprocity",
                                         "Transitive Closure",
                                         "Repetition",
                                         "Cyclic Closure"),
                              subtitle = "- No Shift -")

plots_shift <- create_plots(gam_fit = fit_shift, 
                            ranges = rbind(c(-3,6),
                                           c(-3,3),
                                           c(-3,9),
                                           c(-2.5,2),
                                           c(-2.5,3),
                                           c(-2.5,3),
                                           c(-5,3)),
                            elements = c(1,2,3,4, 5, 6, 7), 
                            labs = c("Internal reciprocal time", 
                                     "Internal transitive time", 
                                     "Internal repeated time", 
                                     "Internal cyclic time", 
                                     "Calendar Time", 
                                     "Day of the Week", 
                                     "Time of the Day"), 
                            titles = c("Reciprocity",
                                       "Transitive Closure",
                                       "Repetition",
                                       "Cyclic Closure",
                                       "Calendar Time", 
                                       "Day of the Week", 
                                       "Time of the Day"),
                            subtitle = "- W/ Shift -")


pdf("pictures/empirical/email/RECIPROCITY_noshift.pdf", width=6, height=6)
plots_noshift[[1]]
dev.off()
pdf("pictures/empirical/email/RECIPROCITY_shift.pdf", width=6, height=6)
plots_shift[[1]]
dev.off()

pdf("pictures/empirical/email/TRANSITIVE_noshift.pdf", width=6, height=6)
plots_noshift[[2]]
dev.off()
pdf("pictures/empirical/email/TRANSITIVE_shift.pdf", width=6, height=6)
plots_shift[[2]]
dev.off()

pdf("pictures/empirical/email/REPETITION_noshift.pdf", width=6, height=6)
plots_noshift[[3]]
dev.off()
pdf("pictures/empirical/email/REPETITION_shift.pdf", width=6, height=6)
plots_shift[[3]]
dev.off()

pdf("pictures/empirical/email/CYCLIC_noshift.pdf", width=6, height=6)
plots_noshift[[4]]
dev.off()
pdf("pictures/empirical/email/CYCLIC_shift.pdf", width=6, height=6)
plots_shift[[4]]
dev.off()

pdf("pictures/empirical/email/CALENDAR_shift.pdf", width=6, height=6)
plots_shift[[5]]
dev.off()

pdf("pictures/empirical/email/DOW_shift.pdf", width=6, height=6)
plots_shift[[6]]
dev.off()

pdf("pictures/empirical/email/TOD_shift.pdf", width=6, height=6)
plots_shift[[7]]
dev.off()
```

```{r}
plots_noshift[[1]]
plots_shift[[1]]
plots_noshift[[2]]
plots_shift[[2]]
plots_noshift[[3]]
plots_shift[[3]]
plots_noshift[[4]]
plots_shift[[4]]
plots_shift[[5]]
plots_shift[[6]]
plots_shift[[7]]
```

