---
title: "Goodness of fit (update)"
author: "Martina Boschi"
date: "2026-08-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data simulation and storage

```{r}
source("script/packages.R")
source("script/GOF.R")
```

```{r}
p <- 20
n_sim <- 100
n <- 2000
set.seed(1234)
source("script/S3_true_nle.R")
```

```{r eval=FALSE}
event_simulator <- function(p, n, seed, fx, distance) {
  
  set.seed(seed)
  print(seed)
  
  current.tm <- 0
  
  dat <- matrix(0, nrow = n, ncol = 7)
  nondat <- matrix(0, nrow = n, ncol = 4)
  
  p2 <- p^2
  all_ids <- 1:p2
  diag_ids <- which(as.vector(diag(p)) == 1)
  
  hazard <- matrix(
    exp(fx(as.vector(distance),
           xlim = dist_range,
           beta = beta_true)),
    nrow = p,
    ncol = p
  ) / p2
  diag(hazard) <- 0
  haz_sum <- sum(hazard)
  
  Lambda_cum <- 0
  Lambda_at_last_event <- 0
  prev_event_time <- 0
  
  for (i in 1:n) {
    
    ## waiting time
    dt <- rexp(1, haz_sum)
    
    current.tm <- current.tm + dt
    
    ## compensator
    Lambda_cum <- Lambda_cum + haz_sum * dt
    compensator_increment <- Lambda_cum - Lambda_at_last_event
    Lambda_at_last_event <- Lambda_cum
    
    interarrival_time <- current.tm - prev_event_time
    prev_event_time <- current.tm
    
    ## event
    event.id <- sample(all_ids, 1, prob = hazard / haz_sum)
    
    s <- (event.id - 1) %% p + 1
    r <- (event.id - 1) %/% p + 1
    
    dat[i, ] <- c(
      current.tm,
      s,
      r,
      event.id,
      distance[s, r],
      haz_sum,
      compensator_increment
    )
    
    ## non-event
    excluded_ids <- union(event.id, diag_ids) 
    non.event.id <- sample(all_ids[-excluded_ids], 1)
    
    non.s <- (non.event.id - 1) %% p + 1
    non.r <- (non.event.id - 1) %/% p + 1
    
    nondat[i, ] <- c(
      non.s,
      non.r,
      non.event.id,
      distance[non.s, non.r]
    )
  }
  
  remdat <- cbind(
    1:n,
    dat,
    nondat,
    dat[, 5] - nondat[, 4],
    1
  )
  
  colnames(remdat) <- c(
    "index",
    "tms",
    "s",
    "r",
    "event.id",
    "distance",
    "tot_rate_at_event",
    "compensator_increment",
    "non.s",
    "non.r",
    "non.event.id",
    "non.distance",
    "delta.dist",
    "one"
  )
  
  as.data.frame(remdat)
}
save(event_simulator, file="output/S3_true_nle_simulator.RData")
```

```{r eval=FALSE}
remdat <- event_simulator(
  p = p, n = n, seed = 1234, fx = fx, 
  distance = dist_matrix
)
summary(diff(remdat$tms))
rescaled <- remdat$compensator_increment
summary(rescaled)
hist(
  rescaled,
  breaks = 50,
  freq = FALSE,
  main = "Rescaled inter-event times",
  xlab = expression(Delta * Lambda)
)
curve(
  dexp(x, rate = 1),
  from = 0,
  to = max(rescaled),
  add = TRUE,
  col = "red",
  lwd = 2
)

ks.test(rescaled, "pexp", rate = 1)
```

```{r eval=FALSE}
remdats <- sapply(1:n_sim, function(x)
  event_simulator(p = p, n = n, seed = x, fx = fx, 
                  distance = dist_matrix),
  simplify = FALSE)

linear_f <- function(x, xlim, beta, df = 10, m = 2) 2*x
remdats_lin <- sapply(1:n_sim, function(x)
  event_simulator(p = p, n = n, seed = x, fx = linear_f, 
                  distance = dist_matrix),
  simplify = FALSE)

gam.fits <- lapply(remdats, function(x) {
  dist_MAT <- cbind(x$distance, x$non.distance)
  ONE <- cbind(x$one, -x$one)
  fit <- gam(one ~ s(dist_MAT, by = ONE) - 1,
             family = "binomial", data = x)
  return(fit)
})

gam.fits_lin <- lapply(remdats_lin, function(x) {
  fit <- gam(one ~ delta.dist - 1,
             family = "binomial", data = x)
  return(fit)
})

gam.fits_lin_mis <- lapply(remdats, function(x) {
  fit <- gam(one ~ delta.dist - 1,
             family = "binomial", data = x)
  return(fit)
})

distance_lin = unlist(lapply(gam.fits_lin, function(x) x$coefficients[1]))
boxplot(distance_lin)
abline(h=2, col=2)

b.dist <- lapply(gam.fits, getViz)
xg <- seq(min(dist_range), 
          max(dist_range), length = 200)
data <- data.frame(x = xg,
                   y = fx(xg, xlim = dist_range, beta_true)-0.1)

coefficients_plot <- ggplot(data=data, aes(x, y)) +
  geom_line(data=data,
            linetype = 1, col="darkblue",
            size=1)
for (iter in 1:n_sim){
  b.iter <- b.dist[[iter]]
  o.iter <- plot(sm(b.iter, 1))
  coefficients_plot <- coefficients_plot + 
    geom_line(data=o.iter$data$fit, 
              linetype = 3, col="lightblue", 
              size=0.5)
}
coefficients_plot <- coefficients_plot +
  labs(
    title = "Estimated vs True Non-linear Effect",
    x = "Covariate",
    y = "Log-hazard contribution"
  ) + theme(legend.position = "none")
coefficients_plot +
  geom_line(data=data,
            linetype = 1, col="darkblue",
            size=1)

save(n, p, fx, dist_matrix, n_sim,
     remdats, remdats_lin,
     gam.fits, gam.fits_lin, gam.fits_lin_mis,
     file="output/S3_true_nle_simulation.RData")
```

```{r}
load(file="output/S3_true_nle_simulation.RData")
```

## Goodness of fit evaluation via martingale residuals

```{r}
remdat_nle <- remdats[[7]]
remdat_lin <- remdats_lin[[7]]
rem_fit_nle <- gam.fits[[7]]
rem_fit_lin <- gam.fits_lin_mis[[7]]
```

### Time specification

```{r}
gof_test_time <- GOF_test(rem_fit = rem_fit_nle, 
                          time = remdat_nle$tms,
                          term = "dist_MAT",
                          test  = "time",
                          main = "Correct time specification",
                          subtitle = "",
                          seed = 1234)
pdf("pictures/gof/S3_true_nle_GOF_test_true_nle_time.pdf")
gof_test_time$pvalue
gof_test_time$plot_fn()
dev.off()
```

### Covariate functional form specification

```{r}
gof_test_cov <- GOF_test(rem_fit = rem_fit_lin, 
                          covariate_event = remdat_nle$distance,
                          covariate_nonevent = remdat_nle$non.distance,
                          test  = "functional_form",
                          main = "Misspecified functional form of covariate effect",
                          subtitle = "",
                          seed = 1234)
pdf("pictures/gof/S3_true_nle_GOF_test_misp_lin.pdf")
gof_test_cov$pvalue
gof_test_cov$plot_fn()
dev.off()
```

## Goodness of fit evaluation via simulation

```{r}
library(relevent)
```

```{r}
remdat <- remdats_lin[[7]]
data_rem <- remdat[,c("tms","s","r","distance")]
colnames(data_rem) <- c("time","sender","receiver", "x")
n_dyads <- p^2
x_array <- array(NA_real_, dim = c(n, n_dyads, 1))
x_matrix <- dist_matrix

fit <- rem.dyad(edgelist=data_rem, n=p, effects="CovEvent", 
                covar=list(CovEvent=x_matrix), gof = FALSE)
```
```{r}
n_sim_boot <- 100
sim_list <- lapply(1:n_sim_boot, function(i){ 
  simulate(fit, covar = list(CovEvent = x_matrix), verbose = FALSE, seed = i)
})
aux_stat <- function(dat, x_matrix) {
  mean(apply(dat, 1, function(x) x_matrix[x[2], x[3]]^2))
}
sim_stats <- sapply(sim_list, function(sim) aux_stat(sim, x_matrix))
observed_stat <- aux_stat(data_rem, x_matrix)
```

```{r}
plot_df <- data.frame(stat = sim_stats)
pdf("pictures/gof/simulated_statistics_true.pdf")
ggplot(plot_df, aes(x = "Simulated (fitted model)", y = stat)) +
  geom_violin(fill = "grey80", alpha = 0.4) +
  geom_jitter(width = 0.05, alpha = 0.3, size = 1) +
  geom_hline(aes(yintercept = observed_stat, color = "Observed"),
             linewidth = 1, linetype = "dashed") +
  scale_color_manual(name = NULL, values = c("Observed" = 2)) +
  labs(y = "Auxiliary statistic", x = NULL,
       title = "Check on auxiliary statistics (true)",
       subtitle = "True: linear effect of x\nFitted: linear effect of x") +
  theme_minimal() +
  theme(legend.position = "top",
        plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 16),
        axis.text = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.key.size = unit(1.2, "cm"),
        legend.key.width = unit(1.8, "cm"),
        axis.line.y = element_line(color = "black", linewidth = 0.5),
        axis.line.x = element_line(color = "black", linewidth = 0.5))
dev.off()
```

```{r}
remdat <- remdats[[7]]
data_rem <- remdat[,c("tms","s","r","distance")]
colnames(data_rem) <- c("time","sender","receiver", "x")
n_dyads <- p^2
x_array <- array(NA_real_, dim = c(n, n_dyads, 1))
x_matrix <- dist_matrix

fit <- rem.dyad(edgelist=data_rem, n=p, effects="CovEvent", 
                covar=list(CovEvent=x_matrix), gof = FALSE)
```

```{r}
n_sim_boot <- 100
sim_list <- lapply(1:n_sim_boot, function(i){ 
  simulate(fit, covar = list(CovEvent = x_matrix), verbose = FALSE, seed = i)
})
aux_stat <- function(dat, x_matrix) {
  mean(apply(dat, 1, function(x) x_matrix[x[2], x[3]]^2))
}
sim_stats <- sapply(sim_list, function(sim) aux_stat(sim, x_matrix))
observed_stat <- aux_stat(data_rem, x_matrix)
```

```{r}
plot_df <- data.frame(stat = sim_stats)
pdf("pictures/gof/simulated_statistics_misp.pdf")
ggplot(plot_df, aes(x = "Simulated (fitted model)", y = stat)) +
  geom_violin(fill = "grey80", alpha = 0.4) +
  geom_jitter(width = 0.05, alpha = 0.3, size = 1) +
  geom_hline(aes(yintercept = observed_stat, color = "Observed"),
             linewidth = 1, linetype = "dashed") +
  scale_color_manual(name = NULL, values = c("Observed" = 2)) +
  labs(y = "Auxiliary statistic", x = NULL,
       title = "Check on auxiliary statistics (mispecified)",
       subtitle = "True: non-linear effect of x\nFitted: linear effect of x") +
  theme_minimal() +
  theme(legend.position = "top",
        plot.title = element_text(hjust = 0.5, size = 18, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5, size = 16),
        axis.text = element_text(size = 16),
        axis.title.y = element_text(size = 16),
        axis.title.x = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.key.size = unit(1.2, "cm"),
        legend.key.width = unit(1.8, "cm"),
        axis.line.y = element_line(color = "black", linewidth = 0.5),
        axis.line.x = element_line(color = "black", linewidth = 0.5))
dev.off()
```

