load("~/Dropbox/Martina/PhD/06-RHEM-non-linear-effects/Empirical-Upload/preliminary_env_fitting.RData")

dat_gam_original <- dat_gam_m1
rm(dat_gam_m1)

k <- floor(nrow(dat_gam_original)/30000)
ind<-seq(1, nrow(dat_gam_original), by = k)

dat_gam <- dat_gam_original[ind,c("IS_OBSERVED_ev",
                      "SOURCE_ev",
                      "TARGET_ev",
                      "TIME_ev", 
                      "source.size_ev",
                      "target.size_ev",
                      "avg.author.publication.activity_ev",
                      "diff.author.publication.activity_ev",
                      "avg.author.citation.popularity_ev",
                      "diff.author.citation.popularity_ev",
                      "paper.outdegree.popularity_ev",
                      "author.sub.rep.1_ev",
                      "author.sub.rep.2_ev",
                      "collaborate.with.citing.author_ev",
                      "reference.sub.rep.1_ev",
                      "reference.sub.rep.2_ev",
                      "author.ref.paper.sub.rep.1.1_ev",
                      "cite.paper.and.its.references.1_ev",
                      "author.self.citation_ev",
                      "IS_OBSERVED_nv",
                      "SOURCE_nv",
                      "TARGET_nv",
                      "TIME_nv",
                      "source.size_nv",
                      "target.size_nv",
                      "avg.author.publication.activity_nv",
                      "diff.author.publication.activity_nv",
                      "avg.author.citation.popularity_nv",
                      "diff.author.citation.popularity_nv",
                      "paper.outdegree.popularity_nv",
                      "author.sub.rep.1_nv",
                      "author.sub.rep.2_nv",
                      "collaborate.with.citing.author_nv",
                      "reference.sub.rep.1_nv",
                      "reference.sub.rep.2_nv",
                      "author.ref.paper.sub.rep.1.1_nv",
                      "cite.paper.and.its.references.1_nv",
                      "author.self.citation_nv",
                      "y",
                      "transform_diff.author.publication.activity_ev",
                      "transform_diff.author.publication.activity_nv",
                      "transform_diff.author.publication.activity",
                      "transform_avg.author.citation.popularity_ev",
                      "transform_avg.author.citation.popularity_nv",
                      "transform_avg.author.citation.popularity",
                      "transform_diff.author.citation.popularity_ev",
                      "transform_diff.author.citation.popularity_nv",
                      "transform_diff.author.citation.popularity",
                      "transform_paper.outdegree.popularity_ev",
                      "transform_paper.outdegree.popularity_nv",
                      "transform_paper.outdegree.popularity",
                      "transform_author.sub.rep.1_ev",
                      "transform_author.sub.rep.1_nv",
                      "transform_author.sub.rep.1",
                      "transform_author.sub.rep.2_ev",
                      "transform_author.sub.rep.2_nv",
                      "transform_author.sub.rep.2",
                      "transform_collaborate.with.citing.author_ev",
                      "transform_collaborate.with.citing.author_nv",
                      "transform_collaborate.with.citing.author",
                      "transform_reference.sub.rep.1_ev",
                      "transform_reference.sub.rep.1_nv",
                      "transform_reference.sub.rep.1",
                      "transform_reference.sub.rep.2_ev",
                      "transform_reference.sub.rep.2_nv",
                      "transform_reference.sub.rep.2",
                      "transform_author.ref.paper.sub.rep.1.1_ev",
                      "transform_author.ref.paper.sub.rep.1.1_nv",
                      "transform_author.ref.paper.sub.rep.1.1",
                      "transform_cite.paper.and.its.references.1_ev",
                      "transform_cite.paper.and.its.references.1_nv",
                      "transform_cite.paper.and.its.references.1",
                      "transform_author.self.citation_ev",
                      "transform_author.self.citation_nv",
                      "transform_author.self.citation",
                      "transformed_time")]
save(dat_gam, file="dat_gam.RData")
